<a href="https://colab.research.google.com/github/krushna1133/NNDL-Practical/blob/main/NNDL_Practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
vector1 = np.array([10,20,30])
vector2 = np.array([5,10,15])
print("Vector1 : ", vector1)
print("Vector2 : ", vector2)
print("Addition: ", vector1 + vector2)

Vector1 :  [10 20 30]
Vector2 :  [ 5 10 15]
Addition:  [15 30 45]


In [18]:
vector3 = np.array([[10,20,30], [5,6,10]])
print("Vector3: \n", vector3)

vector4 = np.array([[40,50], [20,25],[30,40]])
print("\nVector4: \n", vector4)

#multiplication using @
mul = vector3 @ vector4
print("\nMultiplication using @: \n", multi)
#multiplication using np.matmul
multi = np.matmul(vector3, vector4)
print("\nMultiplication using matmul: \n",multi)

Vector3: 
 [[10 20 30]
 [ 5  6 10]]

Vector4: 
 [[40 50]
 [20 25]
 [30 40]]

Multiplication using @: 
 [[1700 2200]
 [ 620  800]]

Multiplication using matmul: 
 [[1700 2200]
 [ 620  800]]
