<a href="https://colab.research.google.com/github/krushna1133/NNDL-Practical/blob/main/NNDL_Practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [17]:
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [18]:
from scipy.sparse.csgraph import maximum_bipartite_matching
iris = load_iris()
X = iris.data
y = iris.target
df = pd.DataFrame(X, columns=iris.feature_names)
df['Target'] = y
df.head()
y = (y == 0).astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = Perceptron(
    max_iter=1000,
    eta0=0.1,
    random_state=42
)


In [20]:
# Train model
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print('Predicted Classes: ')
print(y_pred)
print()
print('Actual Classes')
print(y_test)

Predicted Classes: 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]

Actual Classes
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]


In [29]:
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy =', accuracy)
print('confucsion matrix: \n', confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy = 1.0
confucsion matrix: 
 [[20  0]
 [ 0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [31]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


iris = load_iris()
X = iris.data
y = iris.target

# Display first five rows
df = pd.DataFrame(X, columns=iris.feature_names)
df['Target'] = y
print(df.head())

# Convert to binary classification
y = (y == 0).astype(int)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
  X,
  y,
  test_size=0.2,
  random_state=42
)

# Create Perceptron model
model = Perceptron(
max_iter=1000,
eta0=0.1,
random_state=42
)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Predictions
print('\nPredicted Values:')
print(y_pred)
print('\nActual Values:')
print(y_test)

# Confusion Matrix
print('\nConfusion Matrix')
print(confusion_matrix(y_test, y_pred))

# Classification Report
print('\nClassification Report')
print(classification_report(y_test, y_pred))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0  
Accuracy: 1.0

Predicted Values:
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]

Actual Values:
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]

Confusion Matrix
[[20  0]
 [ 0 10]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        10

    accuracy                           1.00        30
  