<a href="https://colab.research.google.com/github/krushna1133/NNDL-Practical/blob/main/NNDL_Practical1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
#Vector addition
vector1 = np.array([10,20,30])
vector2 = np.array([5,10,15])
print("Vector1 : ", vector1)
print("Vector2 : ", vector2)
print("Addition: ", vector1 + vector2)

Vector1 :  [10 20 30]
Vector2 :  [ 5 10 15]
Addition:  [15 30 45]


In [18]:
#Vector multiplication
vector3 = np.array([[10,20,30], [5,6,10]])
print("Vector3: \n", vector3)

vector4 = np.array([[40,50], [20,25],[30,40]])
print("\nVector4: \n", vector4)

#multiplication using @
mul = vector3 @ vector4
print("\nMultiplication using @: \n", multi)
#multiplication using np.matmul
multi = np.matmul(vector3, vector4)
print("\nMultiplication using matmul: \n",multi)

Vector3: 
 [[10 20 30]
 [ 5  6 10]]

Vector4: 
 [[40 50]
 [20 25]
 [30 40]]

Multiplication using @: 
 [[1700 2200]
 [ 620  800]]

Multiplication using matmul: 
 [[1700 2200]
 [ 620  800]]


In [21]:
#Import dataset
#from local storage after download
import pandas as pd
file = pd.read_csv("/content/Student_Performance.csv")
print(file.head())


   student_id  age  gender school_type parent_education  study_hours  \
0           1   14    male      public    post graduate          3.1   
1           2   18  female      public         graduate          3.7   
2           3   17  female     private    post graduate          7.9   
3           4   16   other      public      high school          1.1   
4           5   16  female      public      high school          1.3   

   attendance_percentage internet_access travel_time extra_activities  \
0                   84.3             yes     <15 min              yes   
1                   87.8             yes     >60 min               no   
2                   65.5              no     <15 min               no   
3                   58.1              no   15-30 min               no   
4                   61.0             yes   30-60 min              yes   

  study_method  math_score  science_score  english_score  overall_score  \
0        notes        42.7           55.4           5

In [28]:
#import from kaggle
import kagglehub
# Download latest version
path = kagglehub.dataset_download("kundanbedmutha/student-performance-dataset")
#it gives path
print("Path to dataset files:", path) # /kaggle/input/student-performance-dataset    -----> go to this path and copy path for file
#read using pandas
file1 = pd.read_csv("/kaggle/input/student-performance-dataset/Student_Performance.csv")
print(file.head())

Using Colab cache for faster access to the 'student-performance-dataset' dataset.
Path to dataset files: /kaggle/input/student-performance-dataset
   student_id  age  gender school_type parent_education  study_hours  \
0           1   14    male      public    post graduate          3.1   
1           2   18  female      public         graduate          3.7   
2           3   17  female     private    post graduate          7.9   
3           4   16   other      public      high school          1.1   
4           5   16  female      public      high school          1.3   

   attendance_percentage internet_access travel_time extra_activities  \
0                   84.3             yes     <15 min              yes   
1                   87.8             yes     >60 min               no   
2                   65.5              no     <15 min               no   
3                   58.1              no   15-30 min               no   
4                   61.0             yes   30-60 min   

In [35]:
#upload using python
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("Student_Performance.csv")
print(data.head())

Saving Student_Performance.csv to Student_Performance (6).csv
   student_id  age  gender school_type parent_education  study_hours  \
0           1   14    male      public    post graduate          3.1   
1           2   18  female      public         graduate          3.7   
2           3   17  female     private    post graduate          7.9   
3           4   16   other      public      high school          1.1   
4           5   16  female      public      high school          1.3   

   attendance_percentage internet_access travel_time extra_activities  \
0                   84.3             yes     <15 min              yes   
1                   87.8             yes     >60 min               no   
2                   65.5              no     <15 min               no   
3                   58.1              no   15-30 min               no   
4                   61.0             yes   30-60 min              yes   

  study_method  math_score  science_score  english_score  overall_

In [55]:
#import using url
url ="https://drive.google.com//file//d//1zl7WQ0FNlpa7fW8SsKHhVace3qF4AdNh//view?usp=drive_link"
data1 = pd.read_csv(url)

HTTPError: HTTP Error 404: Not Found

In [57]:
#clone dataset from github
!git clone https://github.com/krushna1133/NNDL-Practical/blob/main/Student_Performance.csv
data2 = pd.read_csv("/content/ repository/data.csv")


fatal: destination path 'Student_Performance.csv' already exists and is not an empty directory.


FileNotFoundError: [Errno 2] No such file or directory: '/content/ repository/data.csv'